### ISSUE TITLE
Is `master` branch required?

### ISSUE THREAD

**Issue by mrinnetmaki** [FHIR/auto-ig-builder#23]
Currently the [Quick Start Guide](https://github.com/FHIR/auto-ig-builder#quick-start-guide) on the README page says:

> 1. Put your IG on GitHub: create a GitHub repository within your own organization, and push your content to GitHub. For compatibility with the publication pipeline, your default branch must be named master, not main. (If you're interested in contributing to remove this limitation, please talk to us at chat.fhir.org)

I did change the default branch to `master` in one of my IG's, and everything was OK. I got http://build.fhir.org/ig/fhir-fi/finnish-smart/branches/ig-description/index.html.

However, I decided to test with another IG that uses `main` as the default branch, and that seemed to work too. At least I saw the result in http://build.fhir.org/ig/fhir-fi/finnish-base-profiles/branches/terminologies/index.html.

Does the requirement for `master` branch as the default only become evident at a later phase in the publication process? Or did someone come talk to you at chat.fhir.org and the limitation is removed and the documentation is just outdated?

**Comment by jmandel** [comment]
You can potentially get by with other branch names but there are some limitations:

* https://build.fhir.org/ig/fhir-fi/finnish-smart/ will not correctly display your default branch (you need additional path segments to specify it explicitly)

* https://fhir.github.io/auto-ig-builder/builds.html will not include information about your default branch

Our current documentation recommends using `master` because of limitations like these; oftentimes users don't understand the full system and they expect all the parts to work. If you understand the limitations above you can probably get away with other default branch names 🙂
